export const STAT_CATEGORIES = {
  goals: {
    route:   '/goals',
    api:     'goals',
    label:   'Goals',
    icon:    '',
    accent:  'blue',
    columns: [
      { key: 'goals',            label: 'G',    title: 'Goals' },
      { key: 'goalsRightFoot',   label: 'RF',   title: 'Right Foot' },
      { key: 'goalsLeftFoot',    label: 'LF',   title: 'Left Foot' },
      { key: 'goalsHead',        label: 'Hd',   title: 'Headers' },
      { key: 'goalsOther',       label: 'Oth',  title: 'Other' },
      { key: 'goalsInsideArea',  label: 'InA',  title: 'Inside Area' },
      { key: 'goalsOutsideArea', label: 'OutA', title: 'Outside Area' },
      { key: 'penaltiesScored',  label: 'Pen',  title: 'Penalties' },
      { key: 'matchesPlayed',    label: 'MP',   title: 'Matches Played' },
    ],
  },
  attempts: {
    route:   '/attempts',
    api:     'attempts',
    label:   'Attempts',
    icon:    '',
    accent:  'cyan',
    columns: [
      { key: 'attemptsTotal',      label: 'Att',  title: 'Total Attempts' },
      { key: 'attemptsOnTarget',   label: 'OnT',  title: 'On Target' },
      { key: 'attemptsOffTarget',  label: 'OffT', title: 'Off Target' },
      { key: 'attemptsBlocked',    label: 'Blk',  title: 'Blocked' },
    ],
  },
  attacking: {
    route:   '/attacking',
    api:     'attacking',
    label:   'Attacking',
    icon:    '',
    accent:  'gold',
    columns: [
      { key: 'assists',  label: 'Ast', title: 'Assists' },
      { key: 'corners',  label: 'Cor', title: 'Corners' },
      { key: 'offsides', label: 'Off', title: 'Offsides' },
      { key: 'dribbles', label: 'Drb', title: 'Dribbles' },
    ],
  },
  distribution: {
    route:   '/distribution',
    api:     'distribution',
    label:   'Distribution',
    icon:    '',
    accent:  'cyan',
    columns: [
      { key: 'passAccuracy',    label: 'PA%',  title: 'Pass Accuracy %' },
      { key: 'passesAttempted', label: 'PsA',  title: 'Passes Attempted' },
      { key: 'passesCompleted', label: 'PsC',  title: 'Passes Completed' },
      { key: 'crossAccuracy',   label: 'CA%',  title: 'Cross Accuracy %' },
      { key: 'crossesAttempted',label: 'CrA',  title: 'Crosses Attempted' },
      { key: 'crossesCompleted',label: 'CrC',  title: 'Crosses Completed' },
      { key: 'freeKicks',       label: 'FK',   title: 'Free Kicks' },
    ],
  },
  defending: {
    route:   '/defending',
    api:     'defending',
    label:   'Defending',
    icon:    '',
    accent:  'muted',
    columns: [
      { key: 'ballsRecovered', label: 'Rec',  title: 'Balls Recovered' },
      { key: 'tacklesTotal',   label: 'Tkl',  title: 'Total Tackles' },
      { key: 'tacklesWon',     label: 'TkW',  title: 'Tackles Won' },
      { key: 'tacklesLost',    label: 'TkL',  title: 'Tackles Lost' },
      { key: 'clearances',     label: 'Clr',  title: 'Clearances' },
    ],
  },
  disciplinary: {
    route:   '/disciplinary',
    api:     'disciplinary',
    label:   'Disciplinary',
    icon:    '',
    accent:  'gold',
    columns: [
      { key: 'foulsCommitted', label: 'FC',  title: 'Fouls Committed' },
      { key: 'foulsSuffered',  label: 'FS',  title: 'Fouls Suffered' },
      { key: 'yellowCards',    label: 'YC',  title: 'Yellow Cards' },
      { key: 'redCards',       label: 'RC',  title: 'Red Cards' },
      { key: 'minutesPlayed',  label: 'Min', title: 'Minutes Played' },
    ],
  },
};

export const POS_COLORS = {
  STRIKER:           '#ef4444',
  FORWARD:           '#f97316',
  ATTACKING_MIDFIELDER: '#f59e0b',
  CENTRAL_MIDFIELDER:'#22c55e',
  MIDFIELDER:        '#22c55e',
  FULL_BACK:         '#3b82f6',
  CENTRE_BACK:       '#6366f1',
  DEFENDER:          '#6366f1',
  GOALKEEPER:        '#8b5cf6',
  UNKNOWN:           '#6b7a99',
};

export const posColor = (pos) => POS_COLORS[pos] || POS_COLORS.UNKNOWN;
