spring.datasource.url=jdbc:postgresql://localhost:5432/ucl_data?characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=543210
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true